#%RAML 1.0
title: Bug report
version: 1.0
types:
  Foo:
    type: object
    properties:
      foo1:
        type: number
        required: true
  BarFromFoo:
    type: Foo
    properties:
      bar1:
        type: string
        required: true
